name: 'Close stale issues and PRs'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 365
          stale-issue-message: 'This issue is stale because it has been open over a year without activity. Remove stale label or comment on it to reset the stale state.'
          stale-issue-label: Stale
          stale-pr-message: 'This PR is stale because it has been open for over a year without activity. Remove stale label or comment on it to reset the stale state.'
          stale-pr-label: Stale
          operations-per-run: 100
          debug-only: true
